# ==============================================================================
# WORKFLOW : Enterprise CI Pipeline - Validation
#
# PURPOSE
#   Validate application changes before they are merged into the main branch.
#
# RESPONSIBILITY
#   - Source code checkout
#   - Dockerfile linting (Hadolint)
#   - Docker image build verification
#   - Container security scan (Trivy)
#   - SBOM generation
#   - Upload build artifacts
#
# THIS WORKFLOW DOES NOT
#   - Push Docker images
#   - Sign container images
#   - Update GitOps repository
#   - Deploy applications
#
# TRIGGER
#   - Pull Request targeting the main branch
#   - Validates application changes before merge
#
# ==============================================================================

name: Enterprise CI Pipeline - Validation

on:
  pull_request:
    branches:
      - main

# ==============================================================================
# JOBS
# ==============================================================================

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: docker.io/jeevanrana78/enterprise-inventory-app
   

    steps:

# ==========================================================
# Source Control
# - Checkout application source code
# ==========================================================

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Generate Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

# ==========================================================
# Quality Gate
# - Dockerfile linting (Hadolint)
# - Dockerfile best practice validation
# ==========================================================

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile

      - name: Show Runner Information
        run: |
          pwd
          whoami
          docker --version
          php --version

# ==========================================================
# Build
# - Display runner information
# - Build Docker image
# - Create latest and immutable image tags
# - Verify Docker image
# ==========================================================

      - name: Build Docker Image
        working-directory: backend
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:latest \
            -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
            

      - name: Verify Docker Images
        run: |
          docker images
          docker image inspect ${{ env.IMAGE_NAME }}:latest
          docker image inspect ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

# ==========================================================
# Security Scanninged
# - Trivy vulnerability scan
# - SBOM generation
# - Upload SBOM artifact
# ==========================================================

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json